// Package session opens every configured source into one flattened set of
// entries: Pleasant caches unlocked by the single harmos master password, and
// external kdbx files by their own credentials (spec §2a — one unlock, all
// sources). Partial failure is the normal case: a source that can't be opened
// is reported as excluded, never fatal.
//
// It is also where "which sources can be edited?" is settled, and the answer is
// structural: a local kdbx source gets a write handle, a Pleasant cache does
// not, because openWith has no branch that could build one for a cache. Nothing
// downstream has to remember the rule.
package session

import (
	"fmt"
	"os"

	"github.com/pottom/harmos/internal/config"
	"github.com/pottom/harmos/internal/secret"
	"github.com/pottom/harmos/internal/source/localkdbx"
	"github.com/pottom/harmos/internal/vault"
)

// Excluded records a source that could not be opened, and why (so search can
// report it as excluded rather than silently missing — spec §2a).
type Excluded struct {
	Source string
	Reason string
	// BadCredential is true when the source failed on a wrong password/keyfile
	// (retryable with a fresh prompt) rather than a missing or corrupt file.
	BadCredential bool
}

// Result is the combined view of every source that opened.
type Result struct {
	Entries  []vault.Entry
	Folders  []vault.Folder
	Excluded []Excluded

	// Handles are the sources that can be written, by name. A source is here
	// only if harmos could write it, so "is this editable?" is answered by
	// whether a handle exists rather than by a flag somebody has to remember to
	// set.
	//
	// Pleasant sources are never in this map, and not by convention: openWith
	// has no branch that builds a handle for one. Their cache is regenerated by
	// sync, so an edit there would be silently thrown away — the way to stop
	// that is for the capability not to exist, rather than for every caller to
	// remember not to use it.
	Handles map[string]*vault.Handle
}

// Writable reports whether this source can be edited.
func (r *Result) Writable(source string) bool { return r.Handles[source] != nil }

// AskFunc supplies a source's password. retry is true when the previous password
// was rejected, so the caller can re-prompt (and say so). interactive reports
// whether the password came from a live prompt: if it did, a wrong password is
// worth re-prompting; if it came from env/keyring/non-TTY, retrying can't help.
// The returned Secret may be zero for keyfile-only or unprotected files.
type AskFunc func(p config.Source, retry bool) (pw secret.Secret, interactive bool, err error)

// maxUnlockAttempts bounds the wrong-password re-prompts per source.
const maxUnlockAttempts = 3

// Open opens every source, resolving each source's password through ask. It
// never fails the whole run for one bad source — a source that can't be opened
// is recorded as excluded.
func Open(cfg *config.Config, ask AskFunc) *Result {
	res := Result{Handles: map[string]*vault.Handle{}}
	for _, p := range cfg.Sources {
		v, h, err := openOne(p, ask)
		if err != nil {
			res.Excluded = append(res.Excluded, Excluded{p.Name, err.Error(), vault.IsBadCredential(err)})
			continue
		}
		res.Entries = append(res.Entries, v.Entries...)
		res.Folders = append(res.Folders, v.Folders...)
		if h != nil {
			res.Handles[p.Name] = h
		}
	}
	return &res
}

// Reload re-reads one source from disk, for after it has been saved. It reuses
// the handle's credentials, so nothing needs to be asked for again.
//
// It returns the source's fresh entries and folders; the caller merges them back
// into whatever it is showing. A source with no handle cannot be reloaded, which
// is the same statement as "cannot be written".
func (r *Result) Reload(source string) (*vault.Vault, error) {
	h := r.Handles[source]
	if h == nil {
		return nil, fmt.Errorf("source %q is not open for writing", source)
	}
	fresh, err := vault.Reopen(h)
	if err != nil {
		return nil, err
	}
	r.Handles[source] = fresh

	v := fresh.Snapshot()
	r.replaceSource(source, v)
	return v, nil
}

// replaceSource swaps one source's entries and folders for a fresh set, leaving
// every other source's alone.
func (r *Result) replaceSource(source string, v *vault.Vault) {
	entries := r.Entries[:0]
	for _, e := range r.Entries {
		if e.Source != source {
			entries = append(entries, e)
		}
	}
	r.Entries = append(entries, v.Entries...)

	folders := r.Folders[:0]
	for _, f := range r.Folders {
		if f.Source != source {
			folders = append(folders, f)
		}
	}
	r.Folders = append(folders, v.Folders...)
}

// openOne resolves a source's password and opens it, re-prompting on a wrong
// password (up to maxUnlockAttempts) so a bad password is caught immediately —
// not only surfaced as an excluded source at the end. It stops early when ask
// returns the same secret again (non-interactive, keyring, or env), since a
// retry then cannot help.
func openOne(p config.Source, ask AskFunc) (*vault.Vault, *vault.Handle, error) {
	if ask == nil {
		return nil, nil, fmt.Errorf("no way to obtain a password for %q", p.Name)
	}
	var last error
	for attempt := range maxUnlockAttempts {
		pw, interactive, err := ask(p, attempt > 0)
		if err != nil {
			return nil, nil, err
		}
		v, h, oerr := openWith(p, pw)
		if oerr == nil {
			return v, h, nil
		}
		if !vault.IsBadCredential(oerr) {
			return nil, nil, oerr // missing or corrupt file — a new password won't help
		}
		last = oerr
		if !interactive {
			break // env/keyring/non-TTY gave a fixed value — retrying can't help
		}
	}
	return nil, nil, last
}

// openWith opens one source, returning a handle only for the kinds harmos may
// write. The Pleasant branch calls the read-only path deliberately: there is no
// expression here that could produce a handle for a cache, so no later change to
// a flag or a condition can accidentally make one writable.
func openWith(p config.Source, pw secret.Secret) (*vault.Vault, *vault.Handle, error) {
	switch p.Type {
	case config.Pleasant:
		v, err := vault.Open(p.Cache, p.Name, vault.Credentials{Password: pw, Keyfile: cacheKeyfile(p.Name)})
		return v, nil, err
	case config.Kdbx:
		src := localkdbx.Source{Name: p.Name, Path: p.Path, Keyfile: p.Keyfile, Password: pw}
		h, err := src.OpenHandle()
		if err != nil {
			return nil, nil, err
		}
		return h.Snapshot(), h, nil
	default:
		return nil, nil, errUnknownType{p.Type}
	}
}

type errUnknownType struct{ t config.Type }

func (e errUnknownType) Error() string { return "unknown source type: " + string(e.t) }

// cacheKeyfile resolves a Pleasant source's cache keyfile by name and returns it
// only when the file is actually present. A cache written before keyfiles existed
// (master-only) has no keyfile on disk, so returning "" lets it still open with
// the master alone until the next sync re-encrypts it with the composite key.
func cacheKeyfile(name string) string {
	path, err := config.DefaultCacheKeyfilePath(name)
	if err != nil {
		return ""
	}
	if _, err := os.Stat(path); err != nil {
		return ""
	}
	return path
}
