package session

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/pottom/harmos/internal/config"
	"github.com/pottom/harmos/internal/edit"
	"github.com/pottom/harmos/internal/secret"
	"github.com/pottom/harmos/internal/vault"
	"github.com/pottom/harmos/internal/vault/vaulttest"
)

func makeKDBX(t *testing.T, path, password, title string) {
	t.Helper()
	vaulttest.Write(t, path, vaulttest.WithPassword(password), vaulttest.WithTitle(title))
}

func writeConfig(t *testing.T, dir string) *config.Config {
	t.Helper()
	body := fmt.Sprintf(`
[[source]]
name  = "work"
type  = "pleasant"
url   = "https://pps:10001"
user  = "u"
cache = %q

[[source]]
name = "personal"
type = "kdbx"
path = %q
`, filepath.Join(dir, "work.kdbx"), filepath.Join(dir, "personal.kdbx"))
	path := filepath.Join(dir, "config.toml")
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	cfg, err := config.Load(path)
	if err != nil {
		t.Fatal(err)
	}
	return cfg
}

func TestOpenAllSources(t *testing.T) {
	dir := t.TempDir()
	makeKDBX(t, filepath.Join(dir, "work.kdbx"), "master", "db-prod")
	makeKDBX(t, filepath.Join(dir, "personal.kdbx"), "personalpw", "router")
	cfg := writeConfig(t, dir)

	ask := func(p config.Source, retry bool) (secret.Secret, bool, error) {
		if p.Type == config.Pleasant {
			return secret.New("master"), false, nil
		}
		return secret.New("personalpw"), false, nil
	}
	res := Open(cfg, ask)

	if len(res.Excluded) != 0 {
		t.Fatalf("unexpected excluded: %+v", res.Excluded)
	}
	got := map[string]string{} // title -> source
	for _, e := range res.Entries {
		got[e.Title] = e.Source
	}
	if got["db-prod"] != "work" {
		t.Errorf("db-prod source = %q, want work", got["db-prod"])
	}
	if got["router"] != "personal" {
		t.Errorf("router source = %q, want personal", got["router"])
	}
}

func TestPartialFailureIsNotFatal(t *testing.T) {
	dir := t.TempDir()
	makeKDBX(t, filepath.Join(dir, "work.kdbx"), "master", "db-prod")
	makeKDBX(t, filepath.Join(dir, "personal.kdbx"), "personalpw", "router")
	cfg := writeConfig(t, dir)

	// wrong master (returned again on retry) → the Pleasant cache is excluded,
	// but personal still opens
	ask := func(p config.Source, retry bool) (secret.Secret, bool, error) {
		if p.Type == config.Pleasant {
			return secret.New("WRONG"), false, nil
		}
		return secret.New("personalpw"), false, nil
	}
	res := Open(cfg, ask)

	if len(res.Excluded) != 1 || res.Excluded[0].Source != "work" {
		t.Fatalf("expected 'work' excluded, got %+v", res.Excluded)
	}
	if len(res.Entries) != 1 || res.Entries[0].Title != "router" {
		t.Fatalf("expected only router to open, got %+v", res.Entries)
	}
}

// A wrong password on the first try is re-prompted and unlocks on the retry —
// caught immediately, not deferred to an excluded-source warning.
func TestRetryUnlocksOnSecondTry(t *testing.T) {
	dir := t.TempDir()
	makeKDBX(t, filepath.Join(dir, "work.kdbx"), "master", "db-prod")
	makeKDBX(t, filepath.Join(dir, "personal.kdbx"), "personalpw", "router")
	cfg := writeConfig(t, dir)

	tries := map[string]int{}
	ask := func(p config.Source, retry bool) (secret.Secret, bool, error) {
		tries[p.Name]++
		if p.Type == config.Pleasant {
			if !retry {
				return secret.New("WRONG"), true, nil // interactive → retry allowed
			}
			return secret.New("master"), true, nil
		}
		return secret.New("personalpw"), false, nil
	}
	res := Open(cfg, ask)

	if len(res.Excluded) != 0 {
		t.Fatalf("nothing should be excluded, got %+v", res.Excluded)
	}
	if tries["work"] < 2 {
		t.Errorf("work should have been re-prompted, got %d attempt(s)", tries["work"])
	}
}

// A non-interactive wrong password (keyring/env) is tried once, not retried.
func TestNonInteractiveWrongPasswordNotRetried(t *testing.T) {
	dir := t.TempDir()
	makeKDBX(t, filepath.Join(dir, "work.kdbx"), "master", "db-prod")
	makeKDBX(t, filepath.Join(dir, "personal.kdbx"), "personalpw", "router")
	cfg := writeConfig(t, dir)

	tries := 0
	ask := func(p config.Source, retry bool) (secret.Secret, bool, error) {
		if p.Type == config.Pleasant {
			tries++
			return secret.New("WRONG"), false, nil // not interactive
		}
		return secret.New("personalpw"), false, nil
	}
	res := Open(cfg, ask)

	if tries != 1 {
		t.Errorf("a non-interactive wrong password should be tried once, got %d", tries)
	}
	if len(res.Excluded) != 1 || res.Excluded[0].Source != "work" {
		t.Fatalf("expected 'work' excluded, got %+v", res.Excluded)
	}
}

// The structural guarantee. A Pleasant cache is regenerated by sync, so an edit
// there would be silently thrown away — and the way harmos stops that is that
// the capability does not exist for one, not that every caller remembers not to
// use it.
func TestPleasantSourceHasNoHandle(t *testing.T) {
	dir := t.TempDir()
	makeKDBX(t, filepath.Join(dir, "work.kdbx"), "master", "db-prod")
	makeKDBX(t, filepath.Join(dir, "personal.kdbx"), "personalpw", "router")
	cfg := writeConfig(t, dir)

	res := Open(cfg, func(p config.Source, _ bool) (secret.Secret, bool, error) {
		if p.Type == config.Pleasant {
			return secret.New("master"), false, nil
		}
		return secret.New("personalpw"), false, nil
	})

	if len(res.Excluded) != 0 {
		t.Fatalf("unexpected excluded: %+v", res.Excluded)
	}
	if len(res.Handles) != 1 {
		t.Fatalf("handles = %d, want exactly one (the kdbx source): %v", len(res.Handles), handleNames(res))
	}
	if res.Writable("work") {
		t.Error("a Pleasant cache must never be writable; sync would discard the edit")
	}
	if !res.Writable("personal") {
		t.Error("a local kdbx source should have a handle")
	}
	if _, err := res.Reload("work"); err == nil {
		t.Error("a source with no handle cannot be reloaded either")
	}
}

// Folders come through the session too, empty ones included — the tree is built
// from them rather than inferred from entry paths.
func TestOpenCollectsFolders(t *testing.T) {
	dir := t.TempDir()
	makeKDBX(t, filepath.Join(dir, "work.kdbx"), "master", "db-prod")
	makeKDBX(t, filepath.Join(dir, "personal.kdbx"), "personalpw", "router")
	cfg := writeConfig(t, dir)

	res := Open(cfg, func(p config.Source, _ bool) (secret.Secret, bool, error) {
		if p.Type == config.Pleasant {
			return secret.New("master"), false, nil
		}
		return secret.New("personalpw"), false, nil
	})

	sources := map[string]bool{}
	for _, f := range res.Folders {
		sources[f.Source] = true
	}
	if !sources["work"] || !sources["personal"] {
		t.Errorf("folders should come from both sources, got %v", sources)
	}
}

// After a save the caller needs a view of what is now on disk, and reloading
// must replace only that source's entries.
func TestReloadReplacesOnlyThatSource(t *testing.T) {
	dir := t.TempDir()
	makeKDBX(t, filepath.Join(dir, "work.kdbx"), "master", "db-prod")
	makeKDBX(t, filepath.Join(dir, "personal.kdbx"), "personalpw", "router")
	cfg := writeConfig(t, dir)

	res := Open(cfg, func(p config.Source, _ bool) (secret.Secret, bool, error) {
		if p.Type == config.Pleasant {
			return secret.New("master"), false, nil
		}
		return secret.New("personalpw"), false, nil
	})

	workBefore := countFrom(res.Entries, "work")
	personalBefore := countFrom(res.Entries, "personal")

	h := res.Handles["personal"]
	folder := ""
	for _, f := range res.Folders {
		if f.Source == "personal" {
			folder = f.ID
		}
	}
	if _, err := h.CreateEntry(folder, edit.Draft{Title: "added"}); err != nil {
		t.Fatal(err)
	}
	if err := h.Save(); err != nil {
		t.Fatal(err)
	}

	if _, err := res.Reload("personal"); err != nil {
		t.Fatal(err)
	}

	if got := countFrom(res.Entries, "personal"); got != personalBefore+1 {
		t.Errorf("personal entries %d -> %d, want one more", personalBefore, got)
	}
	if got := countFrom(res.Entries, "work"); got != workBefore {
		t.Errorf("reloading one source changed another: work %d -> %d", workBefore, got)
	}

	// And the handle in the map is the fresh one, so the next save's conflict
	// check compares against what is actually on disk.
	if err := res.Handles["personal"].Save(); err != nil {
		t.Errorf("the reloaded handle should be usable: %v", err)
	}
}

func handleNames(r *Result) []string {
	var out []string
	for name := range r.Handles {
		out = append(out, name)
	}
	return out
}

func countFrom(entries []vault.Entry, source string) int {
	n := 0
	for _, e := range entries {
		if e.Source == source {
			n++
		}
	}
	return n
}
